### ISSUE TITLE
Help with command line args

### ISSUE THREAD

**Issue by andregouws** [frankyeh/DSI-Studio#45]
Hi Frank
Thanks again for a fantastic package.
We are trying to set up a processing pipeline ideally from the command line alone. We are a little stuck with what are probably simple problems - maybe you can help.

1) Can we run the initial "open source files" process (including loading a custom b-table) from the command line directly? (i.e. point the program at a folder that contains a pre-corrected nii.gz file and load a b-table for it.) - we don't think this part of the "rec" command because that is obviously the reconstruction step.
2) While we have run motion correction in other packages, it would be useful to run your motion correction routines on our raw data for comparison - these are DSI data however. Is that possible from the command line?

Thanks for you help.
Andre'

**Comment by frankyeh** [comment]
Hi Andre,

> Can we run the initial "open source files" process (including loading a custom b-table) from the command line directly? (i.e. point the program at a folder that contains a pre-corrected nii.gz file and load a b-table for it.) - we don't think this part of the "rec" command because that is obviously the reconstruction step.

The "src" action may help here.
http://dsi-studio.labsolver.org/Manual/command-line-for-dsi-studio#TOC-Generate-SRC-files-from-DICOM-NIFTI-2dseq-images

> While we have run motion correction in other packages, it would be useful to run your motion correction routines on our raw data for comparison - these are DSI data however. Is that possible from the command line?

Adding --motion_correction=1 with the "rec" will trigger motion
correction in DSI Studio.
The motion correction routine is just updated few days ago, and you
may need to use the most recent DSI Studio version for best
performance.
Moreover, motion correction for DSI data may not work perfectly due to
low SNR at the high b-value. If the routine does not work out for you,
please feel free to let me know.
I can help figure out a way to improve it for your data.

Best,
Frank
