### ISSUE TITLE
Warning: --track_count is not used. Please check command line syntax.

### ISSUE THREAD

**Issue by JohannesWiesner** [frankyeh/DSI-Studio#51]
As described on the [documentation page](http://dsi-studio.labsolver.org/Manual/command-line-for-dsi-studio), I am using the `--track_count` argument for `dsi_studio --action=trk`

>  Whole brain fiber tracking
> 
> dsi_studio --action=src --source=./dwi.nii.gz --bval=./bval --bvec=./bvec --output=./my.src.gz
> dsi_studio --action=rec --source=./my.src.gz --method=4  --param0=1.25  # 4:GQI reconstruction
> dsi_studio --action=trk --source=./my.src.gz.gqi.1.25.fib.gz --track_count=10000000

However, I get the following error:

`Warning: --track_count is not used. Please check command line syntax.`

Instead, `dsi_studio --action=trk` seems to use the `fiber_count` argument? `--track_count` seems to exist only for `dsi_studio --action=atk`? Are those equivalent?

**Comment by frankyeh** [comment]
I am sorry for the mistake in the documentation (corrected).
It should be "fiber_count" as used in --action=trk
http://dsi-studio.labsolver.org/Manual/command-line-for-dsi-studio#TOC-Fiber-tracking

As for atk, it is now using "--track_voxel_ratio" instead of the old
"--track_count"

I am sorry for the hassle caused by this errorous information.
Best regards,
Frank
