### ISSUE TITLE
QT error in Docker container 

### ISSUE THREAD

**Issue by stebo85** [frankyeh/DSI-Studio#92]
Dear DSI studio team,

The current docker container (hou-2024-10-02) doesn't work and fails with a QT error:
```
dsi_studio
DSI Studio version: Hou "���" Oct  2 2024
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Segmentation fault (core dumped)

```

setting QT_DEBUG_PLUGINS=1 doesn't provide much more info:
```
DSI Studio version: Hou "���" Oct  2 2024
qt.core.plugin.factoryloader: checking directory path "/opt/dsi-studio/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Segmentation fault (core dumped)

```

**Comment by frankyeh** [comment]
Sorry about the issue. I will check on it asap.
If possible, could you try other containers as listed here and see which recent one works? 
https://hub.docker.com/r/dsistudio/dsistudio/tags

This may help identify the bug and fix it.

**Comment by frankyeh** [comment]
The command line works on my side, and you may test if this crash is due to the GUI. Likely the container cannot access the X11. 

Other solutions include:

1. Install xcb Plugin in the container
Install the xcb plugin package in the container. For example, on Ubuntu-based containers, run: apt-get install libxcb1 libxcb-util1 libxcb-image0.
2. Set QT_QPA_PLATFORM
Set the QT_QPA_PLATFORM environment variable to xcb before running the Qt application. You can do this by adding export QT_QPA_PLATFORM=xcb to your container's startup script or running QT_QPA_PLATFORM=xcb ./your_qt_app.
3. Verify Container Configuration
Ensure that the container has access to the host's display server or X11 socket. You might need to mount the X11 socket (/tmp/.X11-unix) as a volume in the container.

**Comment by stebo85** [comment]
Dear @frankyeh,

yes, the GUI is crashing. I will try what you suggested.

Thank you
Steffen

**Comment by stebo85** [comment]
that worked. Thank you!
